services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2712:27017
    volumes:
      - mongo_db:/data/db
  api:
    build: /
    container_name: api_c
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      BD_NAME: Bank
      NAME: mongo_db
    depends_on:
      - mongo_db
    volumes:
      - ./:/usr/src/app
      - /app/node_modules
    restart: on-failure

volumes:
  mongo_db: {}
